---
version: "3.6"
name: integrator-project-prod-compose
services:
  integrator-db:
    image: postgres
    restart: always
    container_name: integrator-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=IntegratorUser1*
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_example
    depends_on:
      - integrator-db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"

  integrator-project:
    container_name: integrator_project
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - integrator-db